spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_springboot_mvc_starter
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  liquibase:
    enabled: false
    url: jdbc:postgresql://localhost:5432/dev_springboot_mvc_starter
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/db.changelog-master.yaml

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: f66.springboot_mvc_starter.dto
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30

logging:
  level:
    root: ERROR
    f66.springboot_mvc_starter: INFO
    org.springframework.web: ERROR

cloudinary:
  url: ${CLOUDINARY_URL}

config:
  admin-password: ${ADMIN_PASSWORD}
  default-image-url: https://avatar.iran.liara.run/username?username=
