spring:
  profiles:
    active: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  liquibase:
    enabled: true
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    change-log: classpath:db/changelog/db.changelog-master.yaml

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: f66.springboot_mvc_starter.dto
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30

logging:
  level:
    root: ERROR
    f66.springboot_mvc_starter: ERROR
    org.springframework.web: ERROR

cloudinary:
  url: ${CLOUDINARY_URL}

config:
  admin-password: ${ADMIN_PASSWORD}
  default-image-url: https://avatar.iran.liara.run/username?username=
